name: Update SG Oftersheim Kalender

on:
  schedule:
    - cron: "0 6 * * *"   # jeden Tag um 06:00 Uhr
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    env:
      # Steuerung der Mail-Funktion
      SEND_EMAIL_ON_SUCCESS: ${{ vars.SEND_EMAIL_ON_SUCCESS }}
      SEND_EMAIL_ON_ERROR: ${{ vars.SEND_EMAIL_ON_ERROR }}

      # Graph API Credentials
      SMTP_CLIENT_ID: ${{ secrets.SMTP_CLIENT_ID }}
      SMTP_CLIENT_SECRET: ${{ secrets.SMTP_CLIENT_SECRET }}
      SMTP_TENANT_ID: ${{ secrets.SMTP_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # wichtig für Push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 ics msal

      - name: Run calendar generator
        id: runscript
        run: |
          python generate_calendars.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update calendars" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
