name: Update SG Oftersheim Kalender

on:
  schedule:
    - cron: "0 6 * * *"   # jeden Tag um 06:00 Uhr
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # <<< WICHTIG!

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 ics

      - name: Run calendar generator
        id: runscript
        run: |
          python generate_calendars.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update calendars" || echo "No changes to commit"
          git push

      # ---------------------------------------------------------
      # SUCCESS EMAIL (nur wenn ENABLE_EMAIL == true)
      # ---------------------------------------------------------
      - name: Send success email
        if: success() && env.ENABLE_EMAIL == 'true'
        uses: dawidd6/action-send-mail@v3
        env:
          ENABLE_EMAIL: ${{ secrets.ENABLE_EMAIL }}
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: "success: ${{ github.run_started_at }}"
          to: "it@sg-oftersheim.de"
          from
